var BLUEZ_DBUS_SERVICE_NAME = 'org.bluez';
var BLUEZ_ROOT_OBJ = '/';
var BLUEZ_OBJ_MANAGER_INTERFACE = 'org.freedesktop.DBus.ObjectManager';
var DBUS_PROP_IFACE = 'org.freedesktop.DBus.Properties';
var BLUEZ_ADAPTER_INTERFACE = BLUEZ_DBUS_SERVICE_NAME + '.Adapter1';
var BLUEZ_DEVICE_INTERFACE = BLUEZ_DBUS_SERVICE_NAME + '.Device1';
var BLUEZ_GATT_MANAGER_INTERFACE = BLUEZ_DBUS_SERVICE_NAME + '.GattManager1';
var GATT_SERVICE_IFACE = 'org.bluez.GattService1';
var GATT_CHRC_IFACE =    'org.bluez.GattCharacteristic1';
var GATT_DESC_IFACE =    'org.bluez.GattDescriptor1';
var LE_ADVERTISING_MANAGER_IFACE = 'org.bluez.LEAdvertisingManager1';
var LE_ADVERTISEMENT_IFACE = 'org.bluez.LEAdvertisement1';

var UUIDs = {
    CharacteristicExtendedProperties: '2900',
    CharacteristicUserDescription: '2901',
    ClientCharacteristicConfiguration: '2902',
    ServerCharacteristicConfiguration: '2903'
};

var Dbus = {
    BLUEZ_DBUS_SERVICE_NAME : BLUEZ_DBUS_SERVICE_NAME,
    BLUEZ_ROOT_OBJ : BLUEZ_ROOT_OBJ,
    BLUEZ_OBJ_MANAGER_INTERFACE : BLUEZ_OBJ_MANAGER_INTERFACE,
    DBUS_PROP_IFACE : DBUS_PROP_IFACE,
    BLUEZ_ADAPTER_INTERFACE : BLUEZ_ADAPTER_INTERFACE,
    BLUEZ_DEVICE_INTERFACE :BLUEZ_DEVICE_INTERFACE,
    BLUEZ_GATT_MANAGER_INTERFACE : BLUEZ_GATT_MANAGER_INTERFACE,
    GATT_SERVICE_IFACE : GATT_SERVICE_IFACE,
    GATT_CHRC_IFACE : GATT_CHRC_IFACE,
    GATT_DESC_IFACE : GATT_DESC_IFACE,
    LE_ADVERTISING_MANAGER_IFACE : LE_ADVERTISING_MANAGER_IFACE,
    LE_ADVERTISEMENT_IFACE : LE_ADVERTISEMENT_IFACE
};

module.exports = {
    UUIDs: UUIDs,
    Dbus: Dbus
};
